### global.R

library(shiny)
library(shinyjs)
library(tidyverse)
library(lubridate)
library(fs)
library(exifr)
library(magick)
library(shinyFiles)
library(reactable)
library(glue)
library(shinyWidgets)
#library(taxize)
#library(wikitaxa)


source("R/input_folder_module.R")
source("R/start_up_module.R")
source("R/display_image_sequence_module.R")
source("R/control_image_sequence_module.R")
source("R/image_records_module.R")
source("R/determine_capture_interval.R")
source("R/determine_capture_interval.R")
source("R/shut_down_module.R")
source("R/delete_record.R")
